### ISSUE TITLE
不会使用求指教。

### ISSUE THREAD

**Issue by hnh0000** [WangLeto/SetScreenBrightness#2]
不会使用求指教。

**Comment by WangLeto** [comment]
仅支持 Windows 系统。电脑需要安装过 .net Framework，没有安装的话应该会有提示。进入 release 页面，下载一个 .exe 文件运行。
![snipaste-2019 03 21-12 29](https://user-images.githubusercontent.com/25009314/54733550-30c75d80-4bd5-11e9-8ecc-72f92b38f1e1.jpg)
![snipaste-2019 03 21-12 29_0](https://user-images.githubusercontent.com/25009314/54733557-3755d500-4bd5-11e9-91d4-c4dad7987947.jpg)

**Comment by WangLeto** [comment]
如果感觉不好用，建议试一下这位前辈的：https://github.com/emoacht/Monitorian
